### ISSUE TITLE
[ Not Work on Samsung ]

### ISSUE THREAD

**Issue by alissonlinneker** [whiteoctober/cordova-plugin-app-version#56] opened 2015-06-22 23:12 UTC
Not work on Android 5.1.1, Samsung S5 G900M

**Comment by rjmunro** [comment] 2015-06-22 23:21
But the same code works on other devices?

**Comment by alissonlinneker** [comment] 2015-06-22 23:22
Yes, it works at all and I noticed that it did not work this.

**Comment by alissonlinneker** [comment] 2015-06-30 02:47
How to fix? In most, it is working.

Not work on:

SM-G530BT
GT-S5301B
XT1033
XT1069
D2403
C2304
LG-D325
Venue7 3740
D6633
LG-D805
XT1025

And several other models ...

**Comment by philecom** [comment] 2015-07-08 10:07
Has there been a fixed on this issue?

**Comment by alissonlinneker** [comment] 2015-07-08 10:42
No, the problem remains.

**Comment by janhommes** [comment] 2016-02-22 17:29
+1  

I have the same issue on a Samsung S5 mini running android 4.4.2. Somehow the class AppVersion can not be found. On other devices (e.g. Samsung galaxy note) it runs. Here is the stack trace:
```
02-22 18:28:22.027 30159-30362/com.ubs.coo W/System.err: java.lang.ClassNotFoundException: uk.co.whiteoctober.cordova.AppVersion
02-22 18:28:22.027 30159-30362/com.ubs.coo W/System.err:     at java.lang.Class.classForName(Native Method)
02-22 18:28:22.032 30159-30362/com.ubs.coo W/System.err:     at java.lang.Class.forName(Class.java:251)
02-22 18:28:22.032 30159-30362/com.ubs.coo W/System.err:     at java.lang.Class.forName(Class.java:216)
02-22 18:28:22.032 30159-30362/com.ubs.coo W/System.err:     at org.apache.cordova.PluginManager.instantiatePlugin(PluginManager.java:487)
02-22 18:28:22.032 30159-30362/com.ubs.coo W/System.err:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:167)
02-22 18:28:22.032 30159-30362/com.ubs.coo W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:120)
02-22 18:28:22.032 30159-30362/com.ubs.coo W/System.err:     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
02-22 18:28:22.037 30159-30362/com.ubs.coo W/System.err:     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
02-22 18:28:22.037 30159-30362/com.ubs.coo W/System.err:     at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
02-22 18:28:22.037 30159-30362/com.ubs.coo W/System.err:     at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:27)
02-22 18:28:22.037 30159-30362/com.ubs.coo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-22 18:28:22.037 30159-30362/com.ubs.coo W/System.err:     at android.os.Looper.loop(Looper.java:146)
02-22 18:28:22.037 30159-30362/com.ubs.coo W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
02-22 18:28:22.037 30159-30362/com.ubs.coo W/System.err: Caused by: java.lang.NoClassDefFoundError: uk/co/whiteoctober/cordova/AppVersion
02-22 18:28:22.042 30159-30362/com.ubs.coo W/System.err: 	... 13 more
02-22 18:28:22.042 30159-30362/com.ubs.coo W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "uk.co.whiteoctober.cordova.AppVersion" on path: DexPathList[[zip file "/data/app/com.ubs.coo-10.apk"],nativeLibraryDirectories=[/data/app-lib/com.ubs.coo-10, /vendor/lib, /system/lib]]
02-22 18:28:22.042 30159-30362/com.ubs.coo W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:67)
02-22 18:28:22.042 30159-30362/com.ubs.coo W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
02-22 18:28:22.047 30159-30362/com.ubs.coo W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
02-22 18:28:22.047 30159-30362/com.ubs.coo W/System.err: 	... 13 more
02-22 18:28:22.047 30159-30362/com.ubs.coo I/System.out: Error adding plugin uk.co.whiteoctober.cordova.AppVersion.
02-22 18:28:22.047 30159-30362/com.ubs.coo W/System.err: java.lang.NullPointerException
02-22 18:28:22.047 30159-30362/com.ubs.coo W/System.err:     at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
02-22 18:28:22.047 30159-30362/com.ubs.coo W/System.err:     at org.apache.cordova.PluginManager.exec(PluginManager.java:120)
02-22 18:28:22.047 30159-30362/com.ubs.coo W/System.err:     at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
02-22 18:28:22.047 30159-30362/com.ubs.coo W/System.err:     at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
02-22 18:28:22.047 30159-30362/com.ubs.coo W/System.err:     at com.android.org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
02-22 18:28:22.052 30159-30362/com.ubs.coo W/System.err:     at com.android.org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:27)
02-22 18:28:22.052 30159-30362/com.ubs.coo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-22 18:28:22.052 30159-30362/com.ubs.coo W/System.err:     at android.os.Looper.loop(Looper.java:146)
02-22 18:28:22.052 30159-30362/com.ubs.coo W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
```

Anyone has a solution?

**Comment by janhommes** [comment] 2016-02-23 08:56
Never mind my comment. It was an issue with the dex-stup. I needed to add the dex support to my AndroidManifest.xml.

**Comment by Drarok** [comment] 2018-01-16 18:03
If someone has a Samsung device, could they test to see if this is still an issue? I'll close the ticket shortly if not, since I've no way to test myself.

**Comment by Drarok** [comment] 2018-01-19 11:05
I've got my hands on a Samsung Galaxy S5 running Android 6.0.1, and cannot reproduce the issue above – it works fine and reports the version number as expected.

**Closed by Drarok** 2018-01-19 11:05 UTC
Labels: awaiting feedback
