### ISSUE TITLE
Parse error with cordova version 6.0.0

### ISSUE THREAD

**Issue by MuneebSarfraz94** [whiteoctober/cordova-plugin-app-version#101] opened 2018-04-09 12:52 UTC
i'm trying to install this plugin with my cordova version 6.0.0 but this is giving me some parse error. Earlier it was working fine with cordova version 5.1.1. Complete logs of error is listed below. need urgent help for my project
Failed to install 'cordova-plugin-app-version':TypeError: Uh oh!
Object #<Object> has no method 'parse'
    at handlers.js-module.install (/Users/abdulmuneeb/Documents/Development/prometheus/unionconnect-phone/cordova/platforms/android/cordova/lib/pluginHandlers.js:142:66)
    at Object.ActionStack.process (/Users/abdulmuneeb/Documents/Development/prometheus/unionconnect-phone/cordova/platforms/android/cordova/node_modules/cordova-common/src/ActionStack.js:56:25)
    at Api.addPlugin (/Users/abdulmuneeb/Documents/Development/prometheus/unionconnect-phone/cordova/platforms/android/cordova/Api.js:205:20)
    at handleInstall (/Users/abdulmuneeb/Documents/Development/prometheus/unionconnect-phone/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:601:6)
    at /Users/abdulmuneeb/Documents/Development/prometheus/unionconnect-phone/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:385:28
    at _fulfilled (/Users/abdulmuneeb/Documents/Development/prometheus/unionconnect-phone/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/Users/abdulmuneeb/Documents/Development/prometheus/unionconnect-phone/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/Users/abdulmuneeb/Documents/Development/prometheus/unionconnect-phone/node_modules/cordova/node_modules/q/q.js:749:13)
    at /Users/abdulmuneeb/Documents/Development/prometheus/unionconnect-phone/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/Users/abdulmuneeb/Documents/Development/prometheus/unionconnect-phone/node_modules/cordova/node_modules/q/q.js:108:17)
Error: Uh oh!
Object #<Object> has no method 'parse'

**Comment by DennisSmolek** [comment] 2018-05-02 21:40
Duplicate of #75 
Error is due to your node version

**Comment by DennisSmolek** [comment] 2018-05-09 14:30
Not really, this lib doesn't use parse but it looks like plugman does so not sure what else you'd need to do

**Comment by DennisSmolek** [comment] 2018-06-27 11:47
Closing as duplicate of #75

**Closed by DennisSmolek** 2018-06-27 11:47 UTC
Labels: duplicate
